'use client';import{useMemo,useState}from'react';
const photos=['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=90','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=90','https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=90','https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1400&q=90'];
const amenities=[['⌂','3 спальни'],['◯','До 6 гостей'],['≋','Панорамный бассейн'],['⌁','Быстрый Wi-Fi'],['◇','Частная парковка'],['□','Полная кухня'],['☼','Терраса с видом'],['◌','Кондиционер']];
export default function Home(){const[light,setLight]=useState<number|null>(null);const[cin,setCin]=useState('');const[cout,setCout]=useState('');const[done,setDone]=useState(false);const calc=useMemo(()=>{if(!cin||!cout)return{n:0,t:0};const n=Math.max(0,Math.ceil((+new Date(cout)-+new Date(cin))/86400000));return{n,t:n*42000}},[cin,cout]);return <main><nav><a href="#top" className="logo">CASA AVELA</a><div><a href="#story">О вилле</a><a href="#gallery">Галерея</a><a href="#stay">Условия</a></div><a className="book" href="#book">Выбрать даты</a></nav>
<header id="top"><img src={photos[0]} alt="Современная вилла с видом на море"/><div className="shade"/><div className="hero"><p>Приватная вилла · Эгейское побережье · ДЕМО-КОНЦЕПТ</p><h1>Замедлиться.<br/>Увидеть море.</h1><a href="#story">Открыть дом <span>↓</span></a></div><aside><b>38.° N</b><span>Вымышленная локация</span></aside></header>
<section id="story" className="story"><p>01 / О ВИЛЛЕ</p><div><h2>Тихая архитектура,<br/><i>открытый горизонт.</i></h2><p>Casa Avela — вымышленная вилла с тремя спальнями, построенная вокруг тени, натурального камня и непрерывного вида на воду. Каждая комната открывается наружу, а каждый час принадлежит вам.</p></div></section>
<section className="facts"><article><b>06</b><span>Гостей</span></article><article><b>03</b><span>Спальни</span></article><article><b>03</b><span>Ванные</span></article><article><b>01</b><span>Частный бассейн</span></article><small>ВСЕ ХАРАКТЕРИСТИКИ — ДЕМОНСТРАЦИОННЫЕ</small></section>
<section id="gallery" className="gallery"><button onClick={()=>setLight(0)}><img src={photos[0]} alt="Гостиная виллы"/><span>Открыть галерею · 01/04</span></button><button onClick={()=>setLight(1)}><img src={photos[1]} alt="Минималистичная спальня"/></button><button onClick={()=>setLight(2)}><img src={photos[2]} alt="Интерьер в тёплых тонах"/></button></section>
<section className="amen"><div><p>02 / УДОБСТВА</p><h2>Всё необходимое.<br/>Ничего лишнего.</h2><small>ДЕМО-ХАРАКТЕРИСТИКИ</small></div><div className="amenGrid">{amenities.map(x=><article key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div></section>
<section className="rooms"><article><img src={photos[1]} alt="Главная спальня"/><div><p>ГЛАВНАЯ СПАЛЬНЯ</p><h3>Просыпаться у горизонта.</h3><span>Большая кровать · Ванная · Терраса · ДЕМО</span></div></article><article><img src={photos[2]} alt="Гостиная с выходом наружу"/><div><p>ОБЩЕЕ ПРОСТРАНСТВО</p><h3>Дом продолжается снаружи.</h3><span>Открытая кухня · Гостиная · Столовая в тени · ДЕМО</span></div></article></section>
<section className="film"><img src="https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1900&q=90" alt="Вилла на склоне у моря"/><button aria-label="Воспроизвести концепт-фильм">▶</button><p>КОНЦЕПТ-ФИЛЬМ · ВИДЕО-ЗАГЛУШКА</p></section>
<section className="near"><p>03 / РЯДОМ</p><div><h2>Достаточно близко.<br/><i>Далеко от шума.</i></h2>{[['08 мин','Скрытая бухта'],['14 мин','Рынок в посёлке'],['22 мин','Марина'],['35 мин','Аэропорт']].map(x=><article key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></article>)}<small>Демонстрационное время пути для вымышленной локации.</small></div></section>
<section className="terms" id="stay"><h2>Перед поездкой.</h2>{[['Заезд / выезд','После 15:00 / до 11:00'],['Минимальный срок','3 ночи'],['Правила дома','Без мероприятий · Не курить внутри'],['Отмена','Демо-условия — уточняются при бронировании']].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section>
<section className="faq"><p>ВОПРОСЫ</p>{[['Эта вилла существует?','Нет. Casa Avela — вымышленный демонстрационный проект для портфолио.'],['Бассейн приватный?','В рамках концепта — да. Все характеристики приведены для демонстрации.'],['Можно забронировать по-настоящему?','Нет. Выбор дат и расчёт показывают только пользовательский сценарий.']].map(x=><details key={x[0]}><summary>{x[0]}<span>+</span></summary><p>{x[1]}</p></details>)}</section>
<section id="book" className="booking"><div><p>04 / СПЛАНИРОВАТЬ ОТДЫХ</p><h2>Оставьте место<br/>для моря.</h2><span>ДЕМО-БРОНИРОВАНИЕ · БЕЗ ОПЛАТЫ И ПЕРЕДАЧИ ДАННЫХ</span></div>{done?<div className="confirm"><b>✓</b><h3>Демо-заявка готова.</h3><p>Личные данные не были переданы или сохранены.</p><button onClick={()=>setDone(false)}>Изменить даты</button></div>:<form onSubmit={e=>{e.preventDefault();setDone(true)}}><label>Заезд<input required type="date" value={cin} onChange={e=>setCin(e.target.value)}/></label><label>Выезд<input required type="date" value={cout} min={cin} onChange={e=>setCout(e.target.value)}/></label><label>Гости<select><option>2 гостя</option><option>4 гостя</option><option>6 гостей</option></select></label><div className="total"><span>{calc.n?`${calc.n} ноч. × 42 000 ₽`:'Выберите даты'}</span><b>{calc.t?`${calc.t.toLocaleString('ru-RU')} ₽`:'—'}</b><small>Демонстрационный расчёт</small></div><button disabled={!calc.n}>Оставить заявку</button></form>}</section>
<footer><a className="logo" href="#top">CASA AVELA</a><p>Демо-концепт · Создано Max Volkov · 2026</p><a href="#top">К виду ↑</a></footer>
{light!==null&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Галерея виллы"><button className="x" aria-label="Закрыть" onClick={()=>setLight(null)}>×</button><button aria-label="Предыдущее фото" onClick={()=>setLight((light+photos.length-1)%photos.length)}>←</button><img src={photos[light]} alt={`Фотография виллы ${light+1}`}/><button aria-label="Следующее фото" onClick={()=>setLight((light+1)%photos.length)}>→</button><span>{String(light+1).padStart(2,'0')} / 04</span></div>}</main>}
