'use client';import{useMemo,useState}from'react';
const photos=['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=90','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=90','https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=90','https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1400&q=90'];
const amenities=[['⌂','3 bedrooms'],['◯','6 guests'],['≋','Infinity pool'],['⌁','Fast Wi-Fi'],['◇','Private parking'],['□','Full kitchen'],['☼','Sea terrace'],['◌','Air conditioning']];
export default function Home(){const[light,setLight]=useState<number|null>(null);const[cin,setCin]=useState('');const[cout,setCout]=useState('');const[done,setDone]=useState(false);const calc=useMemo(()=>{if(!cin||!cout)return{n:0,t:0};const n=Math.max(0,Math.ceil((+new Date(cout)-+new Date(cin))/86400000));return{n,t:n*42000}},[cin,cout]);return <main><nav><a href="#top" className="logo">CASA AVELA</a><div><a href="#story">The villa</a><a href="#gallery">Gallery</a><a href="#stay">Stay</a></div><a className="book" href="#book">Check dates</a></nav>
<header id="top"><img src={photos[0]} alt="Modern villa opening toward the sea"/><div className="shade"></div><div className="hero"><p>Private villa · Aegean coast · DEMO CONCEPT</p><h1>A slower way<br/>to see the sea.</h1><a href="#story">Discover the house <span>↓</span></a></div><aside><b>38.° N</b><span>Fictional location</span></aside></header>
<section id="story" className="story"><p>01 / THE HOUSE</p><div><h2>Quiet architecture,<br/><i>open horizons.</i></h2><p>Casa Avela is a fictional three-bedroom retreat designed around shade, stone and uninterrupted water views. Every room opens outdoors; every hour belongs to you.</p></div></section>
<section className="facts"><article><b>06</b><span>Guests</span></article><article><b>03</b><span>Bedrooms</span></article><article><b>03</b><span>Bathrooms</span></article><article><b>01</b><span>Private pool</span></article><small>ALL DETAILS ARE DEMONSTRATION CONTENT</small></section>
<section id="gallery" className="gallery"><button onClick={()=>setLight(0)}><img src={photos[0]} alt="Villa living space"/><span>Open gallery · 01/04</span></button><button onClick={()=>setLight(1)}><img src={photos[1]} alt="Minimal villa bedroom"/></button><button onClick={()=>setLight(2)}><img src={photos[2]} alt="Warm villa interior"/></button></section>
<section className="amen"><div><p>02 / AMENITIES</p><h2>Everything you need.<br/>Nothing you don’t.</h2><small>DEMO CHARACTERISTICS</small></div><div className="amenGrid">{amenities.map(x=><article key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div></section>
<section className="rooms"><article><img src={photos[1]} alt="Primary suite"/><div><p>PRIMARY SUITE</p><h3>Wake with the horizon.</h3><span>King bed · Ensuite · Sea terrace · DEMO</span></div></article><article><img src={photos[2]} alt="Indoor outdoor living area"/><div><p>LIVING SPACE</p><h3>Inside flows outside.</h3><span>Open kitchen · Lounge · Shaded dining · DEMO</span></div></article></section>
<section className="film"><img src="https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1900&q=90" alt="Clifftop villa exterior"/><button aria-label="Play concept film">▶</button><p>CONCEPT FILM · VIDEO PLACEHOLDER</p></section>
<section className="near"><p>03 / NEARBY</p><div><h2>Close enough.<br/><i>Far from noise.</i></h2>{[['08 min','Hidden cove'],['14 min','Village market'],['22 min','Marina'],['35 min','Airport']].map(x=><article key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></article>)}<small>Demo travel times for a fictional location.</small></div></section>
<section className="terms" id="stay"><h2>Know before you stay.</h2>{[['Check-in / out','From 15:00 / by 11:00'],['Minimum stay','3 nights'],['House rules','No events · No indoor smoking'],['Cancellation','Demo policy — confirmed with booking']].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section>
<section className="faq"><p>QUESTIONS</p>{[['Is the villa real?','No. Casa Avela is a fictional portfolio demonstration.'],['Is the pool private?','In this demo concept, yes — all listed characteristics are illustrative.'],['Can I make a real booking?','No. The date and price interface demonstrates the guest journey only.']].map(x=><details key={x[0]}><summary>{x[0]}<span>+</span></summary><p>{x[1]}</p></details>)}</section>
<section id="book" className="booking"><div><p>04 / PLAN YOUR STAY</p><h2>Make space<br/>for the sea.</h2><span>DEMO BOOKING · NO PAYMENT OR DATA TRANSFER</span></div>{done?<div className="confirm"><b>✓</b><h3>Your demo request is ready.</h3><p>No personal information was transmitted or stored.</p><button onClick={()=>setDone(false)}>Change dates</button></div>:<form onSubmit={e=>{e.preventDefault();setDone(true)}}><label>Check in<input required type="date" value={cin} onChange={e=>setCin(e.target.value)}/></label><label>Check out<input required type="date" value={cout} min={cin} onChange={e=>setCout(e.target.value)}/></label><label>Guests<select><option>2 guests</option><option>4 guests</option><option>6 guests</option></select></label><div className="total"><span>{calc.n?`${calc.n} nights × ₽ 42 000`:'Select your dates'}</span><b>{calc.t?`₽ ${calc.t.toLocaleString('ru-RU')}`:'—'}</b><small>Demo calculation</small></div><button disabled={!calc.n}>Request to book</button></form>}</section>
<footer><a className="logo" href="#top">CASA AVELA</a><p>Demo concept · Created by Max Volkov · 2026</p><a href="#top">Return to the view ↑</a></footer>
{light!==null&&<div className="lightbox" role="dialog" aria-modal="true"><button className="x" onClick={()=>setLight(null)}>×</button><button onClick={()=>setLight((light+photos.length-1)%photos.length)}>←</button><img src={photos[light]} alt={`Villa gallery image ${light+1}`}/><button onClick={()=>setLight((light+1)%photos.length)}>→</button><span>{String(light+1).padStart(2,'0')} / 04</span></div>}</main>}
